version: '3.2'

networks:
    fiscal:
        driver: bridge

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - WITH_XDEBUG=true
        networks:
            - fiscal
        depends_on:
            - mariadb
        expose:
            - 9000
    mariadb:
        networks:
            - fiscal
        build:
            context: docker/mariadb
            dockerfile: Dockerfile
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=test